name: build-for-oneplus3

on: workflow_dispatch

jobs:
  build-for-nx508j:
    runs-on: self-hosted
    steps:
      - name: Setting up Build Directories
        run: |
          mkdir ~/bin
          mkdir -p ~/android/lineage
          cd ~/android/lineage
          
      - name: Installing Dependencies from Apt
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev libgnutls28-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          
      - name: Installing "repo" Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          
      - name: Authenticating "repo" with GitHub Account
        run: |
          git config --global user.email "tangytugboat912@gmail.com"
          git config --global user.name "mrug_tangy"
          
      - name: Enabling Caching (not sure)
        run: |
          export USE_CCACHE=1
          export CCACHE_EXEC=/usr/bin/ccache
          ccache -M 25G
          
      - name: Setting Up Local Repo
        run: |
          ~/bin/repo init -u https://github.com/LineageOS/android.git -b lineage-18.1 --git-lfs
          ~/bin/repo sync
          
      - name: Setting Up Build Environment
        run: |
          cd ~/android/lineage
          source build/envsetup.sh
          croot
          breakfast oneplus3
          
      - name: Starting Build Process
        run: |
          croot && mka bacon
      
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: DD-MM-YYYY
      
      - name: Uploading Build to Releases
        uses: softprops/action-gh-release@v1
        with:
          name: "Auto Build ${{ steps.current-time.outputs.formattedTime }}"
          tag_name: v1.0
          prerelease: false
          body: |
            This is an Automatic Release by GitHub Actions.
          files: |
            $OUT/recovery.img
            $OUT/lineage-*-nx508j.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
